### ISSUE TITLE
Add source and javadoc jar in maven repository

### ISSUE THREAD

**Issue by nicolaichuk** [xpenatan/gdx-dragome-backend#14]
Please generate and commit next files in

https://github.com/xpenatan/mvn-repo/tree/master/snapshots/com/badlogicgames/gdx/gdx-backend-dragome/1.0.0-NIGHTLIES

gdx-backend-dragome-1.0.0-NIGHTLIES-sources.jar
gdx-backend-dragome-1.0.0-NIGHTLIES-sources.jar.md5
gdx-backend-dragome-1.0.0-NIGHTLIES-sources.jar.sha1

gdx-backend-dragome-1.0.0-NIGHTLIES-javadoc.jar
gdx-backend-dragome-1.0.0-NIGHTLIES-javadoc.jar.md5
gdx-backend-dragome-1.0.0-NIGHTLIES-javadoc.jar.sha1

something like done this

https://oss.sonatype.org/content/repositories/releases/com/badlogicgames/gdx/gdx-backend-gwt/1.9.5/

**Comment by xpenatan** [comment]
Why sources if you can get from this repo ?

will be tricky changing https://github.com/xpenatan/gdx-dragome-backend/blob/master/build.gradle#L86-L110 for sources because its a fatjar. (dragomeSDK + dependencies + dragome-backend). 

I´ll have to study gradle more to generate it.

**Comment by nicolaichuk** [comment]
>> Why sources if you can get from this repo ?

for support in IDEs with gradle or maven plagins

**Comment by xpenatan** [comment]
JavaDoc and source is include in gradle commit url without 'ALL' tag. (check front page)
