### ISSUE TITLE
Support gdx-freetype

### ISSUE THREAD

**Issue by nicolaichuk** [xpenatan/gdx-dragome-backend#16]
Can you support gdx-freetype extension https://github.com/libgdx/libgdx/tree/master/extensions/gdx-freetype like you support bullet extension in web version?

**Comment by xpenatan** [comment]
Okay. I'll take a look.

**Comment by nicolaichuk** [comment]
Maybe it helps:

https://github.com/metafloor/bwip-js/wiki/Compiling-FreeType

https://github.com/intrigus/gdx-freetype-gwt

**Comment by xpenatan** [comment]
@intrigus  made a gwt version running but didnt release the java gwt code (only the compiled js file). It will be helpful if you contact him to help so we can port to dragome.

**Comment by intrigus** [comment]
Hey^^
Will release the java code soon, if I have time.
Ideally this weekend.

**Comment by nicolaichuk** [comment]
@intrigus How was your weekend? :)

**Comment by intrigus** [comment]
@nicolaichuk My weekend was great^^
I'm working on it right now, but I've encountered some bugs, I have to fix :)

**Comment by intrigus** [comment]
My code is working again :)
I'm optimizing it right now and will publish the finished library soon.

**Comment by nicolaichuk** [comment]
@intrigus Glad to hear it.

**Comment by fpetrola** [comment]
Hi @intrigus, do you need some help to publish your gdx-freetype extension?

**Comment by intrigus** [comment]
Hey, I've just released gdx-freetype for gwt!
Have a look at https://github.com/intrigus/gdx-freetype-gwt

**Comment by xpenatan** [comment]
added at #d3a7f19 . Gradle stuff will come out later. 

Thanks @intrigus
