### ISSUE TITLE
Replase Jetty to Gretty 

### ISSUE THREAD

**Issue by nicolaichuk** [xpenatan/gdx-dragome-backend#17]
you used jetty plugin for gradle web test 

https://github.com/xpenatan/gdx-shadertoy/blob/master/dragome/build.gradle

When try run "jettyRun" task, gradle v3.4 write 

> The Jetty plugin has been deprecated and is scheduled to be removed in Gradle 4.0. Consider using the Gretty (https://github.com/akhikhl/gretty) plugin instead.

It may be worth to use gretty plugin?

https://discuss.gradle.org/t/future-of-jetty-plugin/18722

> This plugin is deprecated and will be removed in Gradle 4.0. Consider using the more feature-rich Gretty plugin instead. 

https://docs.gradle.org/current/userguide/jetty_plugin.html

**Comment by xpenatan** [comment]
Sure, jetty is really slow. takes some minutes to compile in my i7 compared with eclipse 8-20 secs

**Comment by xpenatan** [comment]
done, but still slow. i think its gradle...
