### ISSUE TITLE
Multithreading java to js compile

### ISSUE THREAD

**Issue by nicolaichuk** [xpenatan/gdx-dragome-backend#19]
About slowly compile in https://github.com/xpenatan/gdx-dragome-backend/issues/17

When dragome compile java to js it used only one thread.

Maybe there is possibility enable multithreading dragome compile java to js?

**Comment by xpenatan** [comment]
Something is blocking.  generating with eclipse is super fast.

**Comment by nicolaichuk** [comment]
Dragome spend many time after write log "ClassPath Order" and before write "Compiling classes..."
And when count of class more than 3000 it spend 2-3 minutes for apply filter for all class in single thread use cpu only 10%.

Maybe this logic
https://github.com/xpenatan/gdx-dragome-backend/blob/master/backends/gdx-backend-dragome/src/com/badlogic/gdx/backends/dragome/DragomeConfiguration.java#L122
 can done multithreading?
