### ISSUE TITLE
libGDX 1.9.6 released

### ISSUE THREAD

**Issue by nicolaichuk** [xpenatan/gdx-dragome-backend#32]
http://www.badlogicgames.com/wordpress/?p=3984#comments

Maybe need update dependence gdx-dragome-backend and gdx-shadertoy.

It was updated to latest Sound Manager 2 in new libGDX, maybe need update https://github.com/xpenatan/gdx-dragome-backend/releases/download/LIB/soundmanager2-jsmin.js too.

**Comment by xpenatan** [comment]
SoundManager2 is already to last version (its from 2015 =D ) 1.9.6 works fine with backend ( im always at gdx snapshot =D ).

I´ll be moving repo to new location and I will update shadertoy when its done.

**Comment by xpenatan** [comment]
New repo is up. Check front page.
