### ISSUE TITLE
kotlin-lang?

### ISSUE THREAD

**Issue by Namek** [xpenatan/gdx-dragome-backend#34]
Hi there,
are you aware of whether that backend would work with Kotlin language?

**Comment by xpenatan** [comment]
Never tried.  @fpetrola does dragomeSDK support kotlin ?

**Comment by fpetrola** [comment]
Me neither, never tried kotlin under Dragome. It should be running smoothly if Kotlin it's just a matter of bytecode creation from another syntax, just like Scala that is working alright.

**Comment by nicolaichuk** [comment]
@Namek, see this change 

https://github.com/nosix/dragome-sdk/commit/8ba9839cb5953ecdb2dbaa564a8035ba07adcf55

https://github.com/nosix/dragome-sdk/commit/631db6ab9aec574b41eebabb0971319a81b0d2b7

https://github.com/nosix/dragome-sdk/commit/17c78e4d6084c8c60b90af2aa507caeb5dcfe0a6

maybe

**Comment by Namek** [comment]
Thanks guys, personally I've given up on Kotlin at this point. Please decide whether this issue is to be closed.
