### ISSUE TITLE
How upload in local maven repository?

### ISSUE THREAD

**Issue by nicolaichuk** [xpenatan/gdx-dragome-backend#36]
@xpenatan,  How can i upload now in local maven repository after this change https://github.com/xpenatan/gdx-dragome-backend/commit/3f493375915786c759b29c98debf65a76d40a1b2 ?

**Comment by xpenatan** [comment]
I think you can comment  https://github.com/xpenatan/gdx-dragome-backend/blob/master/deploy.gradle#L12-L16   and call uploadArchives like before.  I'll check when I get home

**Comment by nicolaichuk** [comment]
@xpenatan, it will be better if uploading in local repository may do without any change in file. Only use gradle task or define in command line.

**Comment by xpenatan** [comment]
get the last source and the command below will upload to local mvn repo
```
gradle clean uploadArchives -P local
```
